### PR TITLE
Creating tfrecords with RestNet embedding 

### PR DESCRIPTION
**Pull request by chamathabeysinghe**
Change previous resize and sample functions, 
Add restnet embedding to tfrecord and divide to shards 

To run: 
edit directories in shared.py 
run shared.py -> sampling.py -> lab_image_record.py -> restenet_record.py -> build_tfrecords.py

### CODE REVIEW

**Comment by ThejanW** [comment]
Will review this now @chamathabeysinghe

**Comment by chamathabeysinghe** [comment]
For testing, 
* Set export PYTHONPATH=$HOME/dirWithScripts/:$PYTHONPATH
* If you executing individual scripts you can pass different directories to the script through params but it is easy to use default directories. 
* For default directories create ~/flowchroma/original for the dataset direcotry
* run python3 dataset/utils/shared.py 
* python3 dataset/sampling.py 
* python3 dataset/lab_image_record.py
* python3 dataset/restnet_record.py
* python3 dataset/build_tfrecords.py

**Comment by ThejanW** [comment]
Everything seems to work fine, but I got an error while running `python3 dataset/restnet_record.py` 

**here's the error**
```
Traceback (most recent call last):
  File "dataset/restnet_record.py", line 215, in <module>
    args.checkpoint)
  File "dataset/restnet_record.py", line 24, in __init__
    self.checkpoint_file = maybe_download_inception(checkpoint_source)
  File "/home/thejan/Desktop/FYP/FlowChroma-ThejanW/dataset/embedding/inception_utils.py", line 41, in maybe_download_inception
    raise Exception('Checkpoint not valid: {}'.format(checkpoint_source))
Exception: Checkpoint not valid: /home/thejan/imagenet/inception_resnet_v2_2016_08_30.ckpt
```
I had to download resnet.ckpt from http://download.tensorflow.org/models/inception_resnet_v2_2016_08_30.tar.gz and move the extracted ckpt into `~/imagenet`, then everything worked fine. BTW it's **resnet** not **restnet**

**Comment by chamathabeysinghe** [comment]
The error is because I missed one step in the execution steps. Before executing you have to specify checkpoint_url in the dataset/utils/shared.py or specify it as an argument. Checkpoint url could be ckpt file, tar.gz file or http:// url. 
The above error caused because checkpoint url is set to ~/imagenet/....ckpt file which is not existing. If the URL is specified by default it would download files for every execution.

**Comment by ThejanW** [comment]
thanks @chamathabeysinghe :100:

**Pull request merged**
